### ISSUE TITLE
Problem on My Home Page with Multiple Funded People

### ISSUE THREAD

**Issue by philcarrillo** [weenhanceit/autism-funding#29] opened 2016-09-16 00:21 UTC
No matter which Funded Child you click on the My Home page (if there are multiple children) - the first one always changes state

**Comment by lcreid** [comment] 2016-09-16 04:26
Could you please provide some specific steps to reproduce the problem. I'm not sure what you're describing.

**Comment by philcarrillo** [comment] 2016-09-16 14:53
Apologies for the vagueness, wanted to make sure that I noted the problem before forgetting.   

I have 2 funded children defined in the My Profile in my development database.   On the My Home page, the children are displayed in order that I entered them, with what I'll call a 'block' of name, status line and buttons for new forms.  It is my understanding that when you click on the child's name, the block should collapse and only show the child's name.   There is some behaviour here that I find unexpected.
- I click on My Home and I see two funded children, each with their block fully expanded.
- I click on the "top" child name, the top block collapses (as expected)
- I click on the top child name, the top block expands (as expected)
- I click on the **bottom** child name, the **top** block collapses (unexpected)
- I click on the **bottom** child name, the **top** block expands (unexpected) 
- I note in my browser that the link displayed for both top and bottom names is the same (localhost:3000/#collapseOne)
- if the top block is collapsed and I navigate to another menu item (eg My Profile) and I return to My Home, the first block is collapsed (expected) but expands when I move my cursor, without clicking anything (unexpected)
- there appears to be an onChange or onSelect event (javascript link to localhost3000:/#collapseOne) on the drop down box to select the year.  I haven't checked all possibilities, but selecting the drop down is causing unexpected expansion and collapse of the top block.  Since you can see the same link when hovering over this button, I assume this is all related and therefore I did not fully check or describe this particular manifestation of the problem.

**Comment by lcreid** [comment] 2016-09-18 15:54
I think this is mostly fixed. However, the second-last bullet is interesting. I can't reproduce exactly, but what I notice is that when you navigate back to the home page, the default for the accordion is everything open. Perhaps that gave the impression that a mouse move made the panel open. 

Adding memory of the state of the accordion is worthwhile, but might be considered part of our myriad of UI improvements, and not a bug at this point.

**Comment by lcreid** [comment] 2016-10-08 15:04
I think these are all cleaned up, with the exception of maintaining the state of expand/collapse. This is part of preferences (Issue #30), so I'm closing this issue.

**Closed as completed by lcreid** 2016-10-08 15:04 UTC
Labels: bug, review
