### ISSUE TITLE
TypeError in Invoices#edit

### ISSUE THREAD

**Issue by philcarrillo** [weenhanceit/autism-funding#74] opened 2017-03-09 22:53 UTC
Deleted an application (from a double displayed invoice), saved and when I went back to edit the invoice got an application error

app/models/invoice_allocation.rb:41:in `amount_available'
app/views/invoices/_invoice_allocation.html.erb:13:in `_app_views_invoices__invoice_allocation_html_erb___2609109141747637865_69810927133860'
app/views/invoices/_invoice_allocation_wrapper.html.erb:12:in `block in _app_views_invoices__invoice_allocation_wrapper_html_erb__2629032078826882742_69811110965440'
app/views/invoices/_invoice_allocation_wrapper.html.erb:10:in `_app_views_invoices__invoice_allocation_wrapper_html_erb__2629032078826882742_69811110965440'
app/views/invoices/_enter_invoice_form.html.erb:109:in `block in _app_views_invoices__enter_invoice_form_html_erb__1431314722395196002_69811083385260'
app/views/invoices/_enter_invoice_form.html.erb:5:in `_app_views_invoices__enter_invoice_form_html_erb__1431314722395196002_69811083385260'
app/views/invoices/edit.html.erb:3:in `_app_views_invoices_edit_html_erb__4040823873232800996_69811084422860'

**Comment by lcreid** [comment] 2017-03-13 15:00
I assume you meant "deleted an allocation". Do you mean you deleted it on the back end or via the console? What are the steps to reproduce?

**Comment by lcreid** [comment] 2017-03-20 22:22
Can't reproduce, so closing.

**Closed as completed by lcreid** 2017-03-20 22:22 UTC
Labels: bug, wontfix
